"""baseline schema

Revision ID: 2523574bd75d
Revises: (root)
Create Date: 2026-09-18 19:36:36.875654

**本文件由 `alembic revision [--autogenerate]` 从 `script.py.mako` 生成，
MUST NOT 手改生成的 `op.*` 调用**：结构定义以 `deploy/sql/ddl/**`（权威）与
`src/aicore/repository/models.py`（元数据）为准，改结构要先改那两处、再重新生成。
手改这里等于出现第三份结构定义，而它的漂移没有任何门禁能发现。

降级在生产被 `env.py` 默认拒绝（expand-migrate-contract，spec §2.3）。
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# Alembic 的版本标识（revision 之间靠它们串成链）。
revision: str = "2523574bd75d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """升级到本版本。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "risk_predict_result",
        sa.Column("merchant_id", sa.String(length=32), nullable=False),
        sa.Column("merchant_name", sa.String(length=64), nullable=True),
        sa.Column("risk_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column(
            "risk_level",
            sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="risk_predict_result_risk_level"),
            nullable=False,
        ),
        sa.Column("factors_json", sa.JSON(), nullable=False),
        sa.Column("suggestions_json", sa.JSON(), nullable=True),
        sa.Column(
            "predicted_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("merchant_id"),
    )
    op.create_index("idx_predicted", "risk_predict_result", ["predicted_at"], unique=False)
    op.create_table(
        "vision_qa_log",
        sa.Column("qa_id", sa.String(length=32), nullable=False),
        sa.Column("account_id", sa.String(length=32), nullable=True),
        sa.Column("image_key", sa.String(length=255), nullable=False),
        sa.Column("question", sa.String(length=200), nullable=False),
        sa.Column("answer", sa.String(length=500), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("disclaimer", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("qa_id"),
    )
    op.create_index(
        "idx_account_created", "vision_qa_log", ["account_id", "created_at"], unique=False
    )
    op.create_table(
        "vision_review",
        sa.Column("review_id", sa.String(length=32), nullable=False),
        sa.Column("task_id", sa.String(length=32), nullable=True),
        sa.Column(
            "biz_type",
            sa.Enum(
                "RAW_MATERIAL",
                "CERTIFICATE",
                "INSPECTION_SAMPLE",
                "KITCHEN",
                name="vision_review_biz_type",
            ),
            nullable=False,
        ),
        sa.Column("merchant_id", sa.String(length=32), nullable=True),
        sa.Column("merchant_name", sa.String(length=64), nullable=True),
        sa.Column("batch_id", sa.String(length=32), nullable=True),
        sa.Column("image_keys_json", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "AI_PROCESSING",
                "PENDING",
                "CONFIRMED",
                "REFERRED",
                "REJECTED",
                "ARCHIVED",
                name="vision_review_status",
            ),
            server_default=sa.text("'AI_PROCESSING'"),
            nullable=False,
        ),
        sa.Column(
            "confidence_level",
            sa.Enum("HIGH", "MEDIUM", "LOW", name="vision_review_confidence_level"),
            nullable=True,
        ),
        sa.Column("confidence", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column(
            "markers_count",
            sa.Integer().with_variant(mysql.INTEGER(unsigned=True), "mysql"),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.Column(
            "reviewed_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"), nullable=True
        ),
        sa.PrimaryKeyConstraint("review_id"),
    )
    op.create_index(
        "idx_merchant_created", "vision_review", ["merchant_id", "created_at"], unique=False
    )
    op.create_index("idx_status_created", "vision_review", ["status", "created_at"], unique=False)
    op.create_index("idx_task", "vision_review", ["task_id"], unique=False)
    op.create_table(
        "kitchen_anomaly",
        sa.Column("anomaly_id", sa.String(length=32), nullable=False),
        sa.Column("review_id", sa.String(length=32), nullable=True),
        sa.Column("merchant_id", sa.String(length=32), nullable=True),
        sa.Column("merchant_name", sa.String(length=64), nullable=True),
        sa.Column("stream_id", sa.String(length=64), nullable=False),
        sa.Column("anomaly_type", sa.String(length=64), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column(
            "confidence_level",
            sa.Enum("HIGH", "MEDIUM", "LOW", name="kitchen_anomaly_confidence_level"),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "CONFIRMED", "REJECTED", "ARCHIVED", name="kitchen_anomaly_status"),
            server_default=sa.text("'PENDING'"),
            nullable=False,
        ),
        sa.Column(
            "detected_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            nullable=False,
        ),
        sa.Column(
            "reviewed_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["vision_review.review_id"],
            name="fk_kitchen_anomaly_review",
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("anomaly_id"),
    )
    op.create_index("idx_review", "kitchen_anomaly", ["review_id"], unique=False)
    op.create_index("idx_status", "kitchen_anomaly", ["status", "detected_at"], unique=False)
    op.create_index(
        "idx_stream_detected", "kitchen_anomaly", ["stream_id", "detected_at"], unique=False
    )
    op.create_table(
        "review_verdict",
        sa.Column("review_id", sa.String(length=32), nullable=False),
        sa.Column(
            "action",
            sa.Enum("CONFIRM", "REFER", "REJECT", "ARCHIVE", name="review_verdict_action"),
            nullable=False,
        ),
        sa.Column("comment", sa.String(length=200), nullable=True),
        sa.Column("reviewed_by", sa.String(length=64), nullable=False),
        sa.Column(
            "reviewed_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            nullable=False,
        ),
        sa.Column("authority_written", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("authority_event_id", sa.String(length=32), nullable=True),
        sa.Column(
            "authority_written_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["vision_review.review_id"],
            name="fk_review_verdict_review",
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("review_id"),
    )
    op.create_index("idx_reviewed_at", "review_verdict", ["reviewed_at"], unique=False)
    op.create_table(
        "vision_marker",
        sa.Column("marker_id", sa.String(length=32), nullable=False),
        sa.Column("review_id", sa.String(length=32), nullable=False),
        sa.Column("label", sa.String(length=64), nullable=False),
        sa.Column(
            "level", sa.Enum("HIGH", "MEDIUM", "LOW", name="vision_marker_level"), nullable=False
        ),
        sa.Column("confidence", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("bbox_json", sa.JSON(), nullable=True),
        sa.Column("suggestion", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["vision_review.review_id"],
            name="fk_vision_marker_review",
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("marker_id"),
    )
    op.create_index("idx_review", "vision_marker", ["review_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """回退本版本。基线迁移只撤自己建的表；生产禁用降级。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vision_marker")
    op.drop_table("review_verdict")
    op.drop_table("kitchen_anomaly")
    op.drop_table("vision_review")
    op.drop_table("vision_qa_log")
    op.drop_table("risk_predict_result")
    # ### end Alembic commands ###
